(do
    (def num-int 42)
    (def num-float 3.14)
    (def text "hello")
    (def my-list (list 1 2 3))
    (def my-lambda (lambda (x) x))

    (assert! (== (atom? text) true) "atom? should return true for string atoms")
    (assert! (== (atom? num-int) true) "atom? should return true for number atoms")
    (assert! (== (atom? my-list) false) "atom? should return false for lists")
    (assert! (== (atom? text num-int num-float) true) "atom? should return true if all items are atoms")
    (assert! (== (atom? text my-list) false) "atom? should return false if any item is not an atom")

    (assert! (== (int? num-int) true) "int? should return true for integer shaped atoms")
    (assert! (== (int? num-float) false) "int? should return false for float shaped atoms")
    (assert! (== (int? text) false) "int? should return false for non-integer shaped atoms")
    (assert! (== (int? num-int 100) true) "int? should return true if all items are integers")
    (assert! (== (int? num-int num-float) false) "int? should return false if any item is not an integer")

    (assert! (== (float? num-float) true) "float? should return true for float shaped atoms")
    (assert! (== (float? num-int) false) "float? should return false for integer shaped atoms")
    (assert! (== (float? num-float 1.5) true) "float? should return true if all items are floats")
    (assert! (== (float? num-float num-int) false) "float? should return false if any item is not a float")

    (assert! (== (number? num-int) true) "number? should return true for integers")
    (assert! (== (number? num-float) true) "number? should return true for floats")
    (assert! (== (number? text) false) "number? should return false for strings")
    (assert! (== (number? num-int num-float) true) "number? should return true if all items are numbers")
    (assert! (== (number? num-int text) false) "number? should return false if any item is not a number")

    (assert! (== (string? text) true) "string? should return true for strings")
    (assert! (== (string? num-int) false) "string? should return false for numbers")
    (assert! (== (string? text "world") true) "string? should return true if all items are strings")
    (assert! (== (string? text num-int) false) "string? should return false if any item is not a string")

    (assert! (== (lambda? my-lambda) true) "lambda? should return true for lambdas")
    (assert! (== (lambda? print!) false) "lambda? should return false for natives")
    (assert! (== (lambda? my-lambda (lambda () 1)) true) "lambda? should return true if all items are lambdas")
    (assert! (== (lambda? my-lambda print!) false) "lambda? should return false if any item is not a lambda")

    (assert! (== (native? print!) true) "native? should return true for natives")
    (assert! (== (native? my-lambda) false) "native? should return false for lambdas")
    (assert! (== (native? print! println!) true) "native? should return true if all items are natives")
    (assert! (== (native? print! my-lambda) false) "native? should return false if any item is not a native")

    (assert! (== (callable? my-lambda) true) "callable? should return true for lambdas")
    (assert! (== (callable? print!) true) "callable? should return true for natives")
    (assert! (== (callable? text) false) "callable? should return false for strings")
    (assert! (== (callable? my-lambda print!) true) "callable? should return true if all items are callables")
    (assert! (== (callable? my-lambda text) false) "callable? should return false if any item is not a callable")

    (assert! (== (list? my-list) true) "list? should return true for lists")
    (assert! (== (list? text) false) "list? should return false for atoms")
    (assert! (== (list? my-list (list 4 5)) true) "list? should return true if all items are lists")
    (assert! (== (list? my-list text) false) "list? should return false if any item is not a list")

    (assert! (== (empty? "") true) "empty? should return true for empty strings")
    (assert! (== (empty? ()) true) "empty? should return true for empty lists")
    (assert! (== (empty? my-list) false) "empty? should return false for non-empty lists")
    (assert! (== (empty? "" ()) true) "empty? should return true if all items are empty")
    (assert! (== (empty? "" my-list) false) "empty? should return false if any item is not empty")

    (assert! (== (nil? nil) true) "nil? should return true for nil")
    (assert! (== (nil? false) false) "nil? should return false for false")
    (assert! (== (nil? nil nil) true) "nil? should return true if all items are nil")
    (assert! (== (nil? nil text) false) "nil? should return false if any item is not nil")
)