#ifndef REDUCT_CHAR_IMPL_H
#define REDUCT_CHAR_IMPL_H 1

#include "char.h"

reduct_char_info_t reductCharTable[256] = {
    ['\a'] = {.flags = 0, .upper = '\a', .lower = '\a', .decodeEscape = 0, .encodeEscape = 'a'},
    ['\b'] = {.flags = 0, .upper = '\b', .lower = '\b', .decodeEscape = 0, .encodeEscape = 'b'},
    ['\033'] = {.flags = 0, .upper = '\033', .lower = '\033', .decodeEscape = 0, .encodeEscape = 'e'},
    ['\f'] = {.flags = 0, .upper = '\f', .lower = '\f', .decodeEscape = 0, .encodeEscape = 'f'},
    ['\v'] = {.flags = 0, .upper = '\v', .lower = '\v', .decodeEscape = 0, .encodeEscape = 'v'},
    ['\\'] = {.flags = 0, .upper = '\\', .lower = '\\', .decodeEscape = '\\', .encodeEscape = '\\'},
    ['\''] = {.flags = 0, .upper = '\'', .lower = '\'', .decodeEscape = '\'', .encodeEscape = '\''},
    ['"'] = {.flags = 0, .upper = '"', .lower = '"', .decodeEscape = '"', .encodeEscape = '"'},
    [' '] = {.flags = REDUCT_CHAR_WHITESPACE, .upper = ' ', .lower = ' '},
    ['\t'] = {.flags = REDUCT_CHAR_WHITESPACE, .upper = '\t', .lower = '\t', .decodeEscape = 0, .encodeEscape = 't'},
    ['\n'] = {.flags = REDUCT_CHAR_WHITESPACE, .upper = '\n', .lower = '\n', .decodeEscape = 0, .encodeEscape = 'n'},
    ['\r'] = {.flags = REDUCT_CHAR_WHITESPACE, .upper = '\r', .lower = '\r', .decodeEscape = 0, .encodeEscape = 'r'},
    ['!'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '!', .lower = '!'},
    ['$'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '$', .lower = '$'},
    ['%'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '%', .lower = '%'},
    ['&'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '&', .lower = '&'},
    ['*'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '*', .lower = '*'},
    ['+'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '+', .lower = '+'},
    [','] = {.flags = REDUCT_CHAR_SYMBOL, .upper = ',', .lower = ','},
    ['-'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '-', .lower = '-'},
    ['.'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '.', .lower = '.'},
    ['/'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '/', .lower = '/'},
    [':'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = ':', .lower = ':'},
    [';'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = ';', .lower = ';'},
    ['<'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '<', .lower = '<'},
    ['='] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '=', .lower = '='},
    ['>'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '>', .lower = '>'},
    ['?'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '?', .lower = '?', .decodeEscape = '\?', .encodeEscape = '?'},
    ['@'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '@', .lower = '@'},
    ['^'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '^', .lower = '^'},
    ['_'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '_', .lower = '_'},
    ['`'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '`', .lower = '`'},
    ['|'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '|', .lower = '|'},
    ['~'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '~', .lower = '~'},
    ['{'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '{', .lower = '{'},
    ['}'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '}', .lower = '}'},
    ['['] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '[', .lower = '['},
    [']'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = ']', .lower = ']'},
    ['#'] = {.flags = REDUCT_CHAR_SYMBOL, .upper = '#', .lower = '#'},
    ['0'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '0', .lower = '0', .integer = 0},
    ['1'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '1', .lower = '1', .integer = 1},
    ['2'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '2', .lower = '2', .integer = 2},
    ['3'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '3', .lower = '3', .integer = 3},
    ['4'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '4', .lower = '4', .integer = 4},
    ['5'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '5', .lower = '5', .integer = 5},
    ['6'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '6', .lower = '6', .integer = 6},
    ['7'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '7', .lower = '7', .integer = 7},
    ['8'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '8', .lower = '8', .integer = 8},
    ['9'] = {.flags = REDUCT_CHAR_DIGIT | REDUCT_CHAR_HEX_DIGIT, .upper = '9', .lower = '9', .integer = 9},
    ['A'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'A', .lower = 'a', .integer = 10},
    ['B'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'B', .lower = 'b', .integer = 11},
    ['C'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'C', .lower = 'c', .integer = 12},
    ['D'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'D', .lower = 'd', .integer = 13},
    ['E'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'E', .lower = 'e', .integer = 14},
    ['F'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'F', .lower = 'f', .integer = 15},
    ['G'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'G', .lower = 'g'},
    ['H'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'H', .lower = 'h'},
    ['I'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'I', .lower = 'i'},
    ['J'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'J', .lower = 'j'},
    ['K'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'K', .lower = 'k'},
    ['L'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'L', .lower = 'l'},
    ['M'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'M', .lower = 'm'},
    ['N'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'N', .lower = 'n'},
    ['O'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'O', .lower = 'o'},
    ['P'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'P', .lower = 'p'},
    ['Q'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'Q', .lower = 'q'},
    ['R'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'R', .lower = 'r'},
    ['S'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'S', .lower = 's'},
    ['T'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'T', .lower = 't'},
    ['U'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'U', .lower = 'u'},
    ['V'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'V', .lower = 'v'},
    ['W'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'W', .lower = 'w'},
    ['X'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'X', .lower = 'x'},
    ['Y'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'Y', .lower = 'y'},
    ['Z'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'Z', .lower = 'z'},
    ['a'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT,
        .upper = 'A',
        .lower = 'a',
        .decodeEscape = '\a',
        .integer = 10},
    ['b'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT,
        .upper = 'B',
        .lower = 'b',
        .decodeEscape = '\b',
        .integer = 11},
    ['c'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'C', .lower = 'c', .integer = 12},
    ['d'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT, .upper = 'D', .lower = 'd', .integer = 13},
    ['e'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT,
        .upper = 'E',
        .lower = 'e',
        .decodeEscape = '\033',
        .integer = 14},
    ['f'] = {.flags = REDUCT_CHAR_LETTER | REDUCT_CHAR_HEX_DIGIT,
        .upper = 'F',
        .lower = 'f',
        .decodeEscape = '\f',
        .integer = 15},
    ['g'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'G', .lower = 'g'},
    ['h'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'H', .lower = 'h'},
    ['i'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'I', .lower = 'i'},
    ['j'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'J', .lower = 'j'},
    ['k'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'K', .lower = 'k'},
    ['l'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'L', .lower = 'l'},
    ['m'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'M', .lower = 'm'},
    ['n'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'N', .lower = 'n', .decodeEscape = '\n'},
    ['o'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'O', .lower = 'o'},
    ['p'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'P', .lower = 'p'},
    ['q'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'Q', .lower = 'q'},
    ['r'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'R', .lower = 'r', .decodeEscape = '\r'},
    ['s'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'S', .lower = 's'},
    ['t'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'T', .lower = 't', .decodeEscape = '\t'},
    ['u'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'U', .lower = 'u'},
    ['v'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'V', .lower = 'v', .decodeEscape = '\v'},
    ['w'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'W', .lower = 'w'},
    ['x'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'X', .lower = 'x'},
    ['y'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'Y', .lower = 'y'},
    ['z'] = {.flags = REDUCT_CHAR_LETTER, .upper = 'Z', .lower = 'z'},
};

#endif
